apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 0
  selector:
    matchLabels:
      app: myapp
  template:
    badField: badValue
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp:latest
        ports:
        - containerPort: 8080